# Generated by Django 5.2.7 on 2025-10-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Link to gallery category (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
